#!/usr/bin/env bash
#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Embeds contracts/*.schema.json into templates/_contracts.gen.tpl.
#
# A library chart cannot read its own files at render time (.Files is always
# the including chart's), so the schemas are compiled into a named template.
# contracts/ stays the canonical source; this file is regenerated from it.
#
#   hack/gen-contracts.sh          regenerate
#   hack/gen-contracts.sh --check  fail if the generated file is stale
set -euo pipefail

here=$(cd "$(dirname "$0")/.." && pwd)
out="${here}/templates/_contracts.gen.tpl"

render() {
  echo '{{/* GENERATED by hack/gen-contracts.sh from contracts/*.schema.json. DO NOT EDIT. */}}'
  echo '{{- define "okdp.contracts" -}}'
  # One object {<contract>: <schema>}, keyed by x-okdp-contract.
  jq -cS -s 'map({key: .["x-okdp-contract"], value: .}) | from_entries' \
    "${here}"/contracts/*.schema.json
  echo '{{- end -}}'
}

if [[ "${1:-}" == "--check" ]]; then
  if ! diff -u "${out}" <(render); then
    echo "templates/_contracts.gen.tpl is stale: run hack/gen-contracts.sh" >&2
    exit 1
  fi
  exit 0
fi

render > "${out}"
